backend:
  name: github
  repo: clairemanthey/adventure_blog

media_folder: content/assets
public_folder: ../assets

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    slug: "{{year}}-{{month}}-{{day}} -{{slug}}"
    editor:
      preview: true
    fields:
      - { name: "title", label: "Title" }
      - { name: "date", label: "Publish Date", widget: "datetime" }
      - { name: "description", label: "Description" }
      - { name: "body", label: "Body", widget: "markdown" }
      - { name: "tags", label: "Tags", widget: "tags", separator: ", ", required: false}